### ISSUE TITLE
Error: Can't find native module 'ExpoStt'

### ISSUE THREAD

**Issue by theobaronnat** [anhtuank7c/expo-stt#1]
Hi, there is an error with your plugin:

![image](https://github.com/anhtuank7c/expo-stt/assets/92582290/970fbd76-1796-4449-b328-43cf74ddbd27)

Error come from ExpoSttModule.ts:
 `export default requireNativeModule("ExpoStt");`

Here is part of my package.json: 
`{ "expo": "~48.0.15", "react-native": "0.71.7", "expo-stt": "^0.0.3", [...]}`

**Comment by anhtuank7c** [comment]
Hi, this library does not support Expo Web and Expo Go.
It just support Bare React Native project or Expo but need to generate native code by execute this command `npx expo prebuild --clean` (which will generate ios and android with native code)

**Comment by theobaronnat** [comment]
Okay, indeed I was running the command `expo start --android` instead of `expo run:android`. I no longer have that error, however, it doesn't seem to detect the voice.

![image](https://github.com/anhtuank7c/expo-stt/assets/92582290/d504d9cb-4ac8-41ab-b7dc-50312fb12ff2)

**Comment by anhtuank7c** [comment]
You must enable the host microphone from the emulator setting. It's disabled by default.

**Comment by theobaronnat** [comment]
J'ai déjà activé le microphone. En fait, cela fonctionne en Anglais. Je suis français et donc lorsque je disais des mots en français ça ne fonctionnait pas.
Y a t'il un moyen de définir la langue ?

**Comment by theobaronnat** [comment]
I have already enabled the microphone. Actually, it works for English language. I am French, so when I speak French, it doesn't work.
Is there a way to set the language?

**Comment by theobaronnat** [comment]
I see that on file ExpoSttModule.kt: 
`val options = VoiceRecognizerContractOptions(Locale.getDefault())`

I try, on App.tsx, to change the default locale like this:

`setLocale(locale: string) {
        if (NativeModules.I18nManager) {
            NativeModules.I18nManager.localeIdentifier = locale;
        }
    },`

`console.log(LocaleConfig.getLocale())
LocaleConfig.setLocale('fr_FR');
console.log(LocaleConfig.getLocale())`

The locale has changed, but the recognition language is always in English (United state).

**Comment by anhtuank7c** [comment]
Thank you so much for reporting this.
Actually we need some improvement such as: passing locale code while call `ExpoStt.startSpeech(LOCALE_CODE)` and also throw an exception in case locale is not available on device.
I think we could close this issue and create a new one for that one which stand for a clear purpose.

**Comment by anhtuank7c** [comment]
I've created a new issue for that at https://github.com/anhtuank7c/expo-stt/issues/2

**Comment by theobaronnat** [comment]
I'm glad to hear that the speech recognition is working perfectly once your phone is set to your language. Thank you for your kind words and appreciation! 
I'm looking forward to future improvements as well. If I come across any other areas for improvement, I'll let you know.

**Comment by anhtuank7c** [comment]
You're welcome.
I have a great experience cooperate with a French's dev in the past ^^!
Can we close this one?

**Comment by theobaronnat** [comment]
It's great to hear that :) Of course, we can close this issue !

**Comment by ahadnawaz585** [comment]
ERROR  Error: Cannot find native module 'ExpoStt', js engine: hermes
 
 
 import React, { useState, useEffect } from 'react';
import { View, Text, TouchableOpacity } from 'react-native';
import * as ExpoStt from 'expo-stt';

const SpeechToText = () => {
  const [spokenText, setSpokenText] = useState('');
  const [isRecognizing, setIsRecognizing] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    const onSpeechStart = ExpoStt.addOnSpeechStartListener(() => {
      setSpokenText('');
      setError('');
      setIsRecognizing(true);
    });

    const onSpeechResult = ExpoStt.addOnSpeechResultListener(({ value }) => {
      setSpokenText(value.join());
    });

    const onSpeechCancelled = ExpoStt.addOnSpeechCancelledListener(() => {
      setIsRecognizing(false);
    });

    const onSpeechError = ExpoStt.addOnSpeechErrorListener(({ cause }) => {
      setError(cause);
      setIsRecognizing(false);
    });

    const onSpeechEnd = ExpoStt.addOnSpeechEndListener(() => {
      setIsRecognizing(false);
    });

    return () => {
      onSpeechStart.remove();
      onSpeechResult.remove();
      onSpeechCancelled.remove();
      onSpeechError.remove();
      onSpeechEnd.remove();
    };
  }, []);

  const startSpeechRecognition = async () => {
    try {
      await ExpoStt.startSpeech();
    } catch (error) {
      console.error('Speech recognition error:', error);
    }
  };

  const stopSpeechRecognition = async () => {
    try {
      await ExpoStt.stopSpeech();
    } catch (error) {
      console.error('Speech recognition error:', error);
    }
  };

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Spoken Text: {spokenText}</Text>
      {error ? <Text>Error: {error}</Text> : null}
      <TouchableOpacity
        onPress={isRecognizing ? stopSpeechRecognition : startSpeechRecognition}
        style={{
          marginTop: 20,
          padding: 10,
          backgroundColor: isRecognizing ? 'red' : 'green',
          borderRadius: 5,
        }}>
        <Text style={{ color: 'white' }}>
          {isRecognizing ? 'Stop Recognition' : 'Start Recognition'}
        </Text>
      </TouchableOpacity>
    </View>
  );
};

export default SpeechToText;

    "plugins": [
      "expo-font",
        [
          "expo-stt",
          {
            "microphonePermission": "Allow $(PRODUCT_NAME) to access your microphone",
            "speechRecognitionPermission": "Allow $(PRODUCT_NAME) to access your speech recognition"
          }
      ]
    ],
    
    
![image](https://github.com/anhtuank7c/expo-stt/assets/132939571/5bd18723-fd01-4519-a0c1-fd96126d6a2f)

![image](https://github.com/anhtuank7c/expo-stt/assets/132939571/6d6ff390-a472-4d30-a2e4-d8ddaf0b10f6)


![WhatsApp Image 2024-06-07 at 12 53 43_9af90f52](https://github.com/anhtuank7c/expo-stt/assets/132939571/08110e25-b010-42be-b2d2-59e326694314)



tell me asap !
 where i am doing wrong coz it's not wokring

**Comment by anhtuank7c** [comment]
> ahadnawaz585
This module does not support Expo Go or the web. Please generate native directory if you're using Expo: `npx expo prebuild --clean` or use it with bare React Native project.
